# Generated by Django 5.2.1 on 2025-05-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_full_name",
                    models.CharField(max_length=50, verbose_name="Полное имя"),
                ),
                (
                    "contact_information",
                    models.CharField(
                        max_length=25, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "customer_login",
                    models.CharField(max_length=25, verbose_name="Логин"),
                ),
                (
                    "customer_password",
                    models.IntegerField(max_length=9, verbose_name="Пароль"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateField(verbose_name="Дата создания")),
                (
                    "destination_address",
                    models.CharField(max_length=50, verbose_name="Адрес назначения"),
                ),
                ("type_tc_id", models.IntegerField()),
                ("total_cost", models.IntegerField(verbose_name="Суммарная стоимость")),
                (
                    "date_of_accomplishment",
                    models.DateField(verbose_name="Дата выполнения"),
                ),
                ("administrator_id", models.IntegerField()),
                ("application_status", models.CharField(verbose_name="Статус")),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bd.customer"
                    ),
                ),
            ],
        ),
    ]
